# Generated by Django 3.1.5 on 2022-05-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tasktodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktodo',
            name='title',
            field=models.CharField(default='task1', max_length=122),
        ),
        migrations.AlterField(
            model_name='tasktodo',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
